# Generated by Django 5.0 on 2024-01-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='date_posted',
            new_name='date',
        ),
    ]
