# Generated by Django 5.0 on 2024-01-14 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_date_posted_posts_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='Post',
        ),
    ]
