# Generated by Django 5.0 on 2024-01-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_image/OIP.jpeg', upload_to='post_image'),
        ),
    ]
