# Generated by Django 5.0 on 2024-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_post_likes_comment_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
