# Generated by Django 5.0 on 2024-02-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_topic_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
    ]
